interfaces/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^vistas/', include('vistas.urls')),
    url(r'^$', views.home_redirect, name = 'home_redirect')
]

vistas/urls.py
# -*- coding: utf-8 -*-


from . import views
from django.conf.urls import url
from django.contrib.auth.views import login, logout

app_name = 'vistas'
urlpatterns = [
	url(r'^login/$', views.ingreso, name='ingreso'),
	url(r'^logout/$', views.ingreso, name='salir'),
	url(r'^registro/$', views.registro, name='registro'),
	url(r'^infoNutricional/$', views.infoNutricional, name='infoNutricional'),
	url(r'^juegos/$', views.juegos, name='juegos'),
	url(r'^principalMedico/$', views.principalMedico, name='principalMedico'),
	url(r'^principalMedico/agregarPaciente/$', views.agregarPaciente, name='agregarPaciente'),
	url(r'^principalRepresentante/$', views.principalRepresentante, name='principalRepresentante'),
	url(r'^principalRepresentante/agregarCita$', views.agregarCita, name='agregarCita'),
	url(r'^principalRepresentante/agregarRepresentado/$', views.agregarRepresentado, name='agregarRepresentado'),
	url(r'^principalRepresentante/agregarRepresentado/(?P<ciPaciente>.+)/$', views.agregarARepresentante, name='agregarARepresentante'),
	url(r'^principalProfesor/$', views.principalProfesor, name='principalProfesor'),
	url(r'^principalProfesor/agregarAlumno/$', views.agregarAlumno, name='agregarAlumno'),
	url(r'^home/$', views.home, name='home'),
	url(r'^perfil/$', views.perfil, name = 'perfil'),
	url(r'^perfilPaciente/(?P<ciPaciente>.+)/$', views.perfilPaciente, name='perfilPaciente'),
	url(r'^listajuegos/$', views.listajuegos, name='listajuegos'),

]

vistas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime, hashlib

# Create your models here.
class Usuario(models.Model):
    username    = models.EmailField(max_length=50, primary_key=True)
    password    = models.CharField(max_length=64, null=False)
    nombres     = models.CharField(max_length=80)
    apellidos   = models.CharField(max_length=80)

    def crearUsuario(self,usr,pwd):

        try:
            self.username = usr
            m = hashlib.sha256()
            p = str.encode(pwd)
            m.update(p)
            self.password = m.hexdigest()
            self.save()
            return True
        except:
            return False

    # Extrae por defecto el nombre de usuario
    def __str__(self):
        return self.username

    class Meta:
        app_label = 'vistas'

class Paciente(models.Model):
	nombres = models.CharField(max_length=80)
	apellidos = models.CharField(max_length=80)
	ci = models.CharField(max_length=9, primary_key=True)
	nacimiento = models.DateField()
	enfermedad = models.CharField(max_length=80)

class Dieta(models.Model):
    paciente = models.OneToOneField(Paciente, on_delete=models.PROTECT)
    hora = models.CharField(max_length=80)
    porcion = models.CharField(max_length=80)
    alimento = models.CharField(max_length=80)

class Medico(models.Model):
	usuario = models.OneToOneField(Usuario, on_delete=models.PROTECT, primary_key=True)
	especialidad = models.CharField(max_length=80, blank=True)
	pacientes = models.ManyToManyField(Paciente, blank=True)


class Profesor(models.Model):
	usuario = models.OneToOneField(Usuario, on_delete=models.PROTECT, primary_key=True)
	area = models.CharField(max_length=80, blank=True)
	alumnos = models.ManyToManyField(Paciente, blank=True)

class Representante(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.PROTECT, primary_key=True)
    representa = models.ManyToManyField(Paciente, blank=True)

class Cita(models.Model):
    medico = models.ForeignKey(Medico, on_delete=models.PROTECT)
    representante = models.ForeignKey(Representante, on_delete=models.PROTECT)
    fecha = models.DateField()
    hora = models.CharField(max_length=6)

'''
Funciones auxiliares
'''

def esMedico(usr):
    try:
        med = Medico.objects.get(pk=usr)
        return True
    except:
        return False

def esProfesor(usr):
    try:
        prof = Profesor.objects.get(pk=usr)
        return True
    except:
        return False

def esRepresentante(usr):
    try:
        rep = Representante.objects.get(pk=usr)
        return True
    except:
        return False

vistas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *
import hashlib, datetime
import re

CHOICES = [('Medico', 'Medico'), ('Profesor', 'Profesor'), ('Representante', 'Representante')]

class RegistroUsuarioForm(forms.ModelForm):
	tipo = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)
	
	class Meta:
		model = Usuario
		fields = [
			'username',
			'nombres',
			'apellidos',
			'password',
			
		]
		labels = {
			'username': 'Correo electronico',
			'nombres': 'Nombres',
			'apellidos': 'Apellidos',
			'password': 'Contrasena',
			
		}
		widgets = {
			'username': forms.EmailInput(attrs={'class':'input100', 'placeholder': 'Correo electronico'}),
			'nombres': forms.TextInput(attrs={'class':'input100', 'placeholder': 'Nombres'}),
			'apellidos': forms.TextInput(attrs={'class':'input100', 'placeholder': 'Apellidos'}),
			'password': forms.PasswordInput(attrs={'class':'input100', 'placeholder': 'Password', 'type': 'password'}),

		}

class ModificarUsuarioForm(forms.ModelForm):
	
	class Meta:
		model = Usuario
		fields = [
			'username',
			'nombres',
			'apellidos',
			'password',
			
		]
		labels = {
			'username': 'Correo electronico',
			'nombres': 'Nombres',
			'apellidos': 'Apellidos',
			'password': 'Contrasena',
			
		}
		widgets = {
			'username': forms.EmailInput(attrs={'class':'form-control', 'placeholder': 'Correo electronico'}),
			'nombres': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Nombres'}),
			'apellidos': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Apellidos'}),
			'password': forms.PasswordInput(attrs={'class':'form-control', 'placeholder': 'Password', 'type': 'password'}),

		}


class LoginUsuarioForm(forms.Form):

	username = forms.EmailField(max_length=30, widget=forms.EmailInput(attrs={'class':'input100', 'placeholder': 'Correo electronico'}))
	password = forms.CharField(max_length=64, widget=forms.PasswordInput(attrs={'class':'input100', 'placeholder': 'Password', 'type': 'password'}))

	def clean(self):
		limpio = super(LoginUsuarioForm, self).clean()
		usr = limpio.get('username')
		pwd = limpio.get('password')
		try:
			q = Usuario.objects.get(pk=usr)
			m = hashlib.sha256()
			p = str.encode(pwd)
			m.update(p)

			if (m.hexdigest()==q.password):
				pass
				#self.usuario = q
			else:
				self.add_error('username', 'Usuario o clave incorrecto')
		except:
			self.add_error('username', 'Usuario o clave incorrecto')
		return limpio

	class Meta:
		model = Usuario

		exclude = [
			'nombres',
			'apellidos'
		]

class AgregarAlumnoForm(forms.ModelForm):

	class Meta:
		model = Paciente

		exclude = []

		widgets = {
			'nombres': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombres'}),
			'apellidos': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellidos'}),
			'ci': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'C.I'}),
			'nacimiento': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'aaaa-mm-dd'}),
			'enfermedad': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enfermedad'}),
		}


		
class AgregarPacienteForm(forms.ModelForm):

	class Meta:
		model = Paciente

		exclude = []

		widgets = {
			'nombres': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombres'}),
			'apellidos': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellidos'}),
			'ci': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'C.I'}),
			'nacimiento': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'aaaa-mm-dd'}),
			'enfermedad': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enfermedad'}),
		}

class AgregarCitaForm(forms.ModelForm):

	class Meta:
		model = Cita

		exclude = ['representante']

		widgets = {
			'medico': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Medicos'}),
			'fecha': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'aaaa-mm-dd'}),
			'hora': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Hora'}),

		}

vistas/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout
from .forms import *
from .models import *
# Create your views here.
def ingreso(request):

	if request.method == 'POST':
		form = LoginUsuarioForm(request.POST)
		
		#print("Entre en method")
		#print(form['username'].value())
		objeto = get_object_or_404(Usuario, pk=form['username'].value())
		if form['password'].value() == objeto.password:
			
			request.session['username'] = objeto.username
			if esMedico(objeto):
				return redirect('/vistas/principalMedico')
			elif esProfesor(objeto):
				return redirect('/vistas/principalProfesor')
			elif esRepresentante(objeto):
				return redirect('/vistas/principalRepresentante')			
		
	else:
		form = LoginUsuarioForm()
		
	return render(request, 'vistas/login.html', {'form': form})

def registro(request):
	
	if request.method == 'POST':
		form = RegistroUsuarioForm(request.POST)
		
		if form.is_valid():
			#print(form['tipo'].value())
			form.save()
			usr = Usuario.objects.get(pk=form['username'].value())
			if form['tipo'].value() == 'Medico':
				med = Medico(usuario=usr)
				med.save()
			elif form['tipo'].value() == 'Profesor':
				prof = Profesor(usuario=usr)
				prof.save()
			elif form['tipo'].value() == 'Representante':
				rep = Representante(usuario=usr)
				rep.save()
			
			return redirect('/vistas/login')
	else:
		form = RegistroUsuarioForm()
	return render(request, 'vistas/registro.html', {'form': form})

'''
Informacion nutricional
'''
def infoNutricional(request):
	return render(request, 'vistas/infoNutricional.html', {})

'''
Juegos
'''
def juegos(request):
	usuario = get_object_or_404(Usuario, pk=request.session['username'])


	args = {'usuario': usuario}
	return render(request, 'vistas/juegos.html', args)

'''
Vistas del medico
'''
def principalMedico(request):
	usuario = get_object_or_404(Medico, pk=request.session['username'])
	citas = Cita.objects.filter(medico=usuario)
	args = {'usuario': usuario, 'citas': citas}
	return render(request, 'vistas/principalMedico.html', args)

def agregarPaciente(request):
	usuario = get_object_or_404(Medico, pk=request.session['username'])

	if request.method == 'POST':
		form = AgregarPacienteForm(request.POST)
		if form.is_valid():
			form.save()
			#Agregar a maedico#
			#usuario = get_object_or_404(Medico, pk=request.session['username'])
			pacienteNuevo = Paciente.objects.get(pk=form['ci'].value())
			usuario.paciente.add(pacienteNuevo)
			return redirect('/vistas/principalMedico')
	else:
		form = AgregarPacienteForm()
	args = {'usuario': usuario, 'form': form}
	return render(request, 'vistas/agregarPaciente.html', args)

def eliminarPaciente(request, ciPaciente):
	usuario = get_object_or_404(Usuario, pk=request.session['username'])
	paciente = Paciente.objects.get(pk=ciPaciente)
	paciente.delete()
	if esMedico(usuario.username):
		return redirect('/vistas/principalMedico/')
	elif esProfesor(usuario.username):
		return redirect('/vistas/principalProfesor/')
	elif esRepresentante(usuario.username):
		return redirect('/vistas/principalRepresentante/')
	else:
		return redirect('/vistas/login/')

'''
Vistas del representante
'''

def principalRepresentante(request):
	usuario = get_object_or_404(Representante, pk = request.session['username'])
	citas = Cita.objects.filter(representante=usuario)
	args = {'usuario': usuario, 'citas': citas}
	return render(request, 'vistas/principalRepresentante.html', args)

def agregarCita(request):
	usuario = get_object_or_404(Representante, pk=request.session['username'])

	if request.method == 'POST':
		form = AgregarCitaForm(request.POST)
		if form.is_valid():
			nuevaCita = form.save(commit=False)
			nuevaCita.representante = usuario
			nuevaCita.save()
			return redirect('/vistas/principalRepresentante')
		
	else:
		form = AgregarCitaForm()
	args = {'usuario': usuario, 'form': form}
	return render(request, 'vistas/agregarCita.html', args)


def agregarRepresentado(request):
	usuario = get_object_or_404(Representante, pk=request.session['username'])
	pacientes = Paciente.objects.all()

	args = {'usuario': usuario, 'pacientes': pacientes}
	return render(request, 'vistas/agregarRepresentado.html', args)

def agregarARepresentante(request, ciPaciente):
	usuario = get_object_or_404(Representante, pk=request.session['username'])

	nuevopaciente = Paciente.objects.get(pk=ciPaciente)
	usuario.representa.add(nuevopaciente)
	
	args = {'usuario': usuario}
	return redirect('/vistas/principalRepresentante')

def eliminarCita(request, citaId):
	usuario = get_object_or_404(Representante, pk=request.session['username'])
	cita = Cita.objects.get(pk=citaId)
	cita.delete()
	return redirect('/vistas/principalRepresentante/')


'''
Vistas del profesor
'''

def principalProfesor(request):
	usuario = get_object_or_404(Profesor, pk=request.session['username'])
	args = {'usuario': usuario}
	return render(request, 'vistas/principalProfesor.html', args)

def agregarAlumno(request):
	usuario = get_object_or_404(Profesor, pk=request.session['username'])

	if request.method == 'POST':
		form = AgregarPacienteForm(request.POST)
		if form.is_valid():
			form.save()
			#Agregar a maedico#
			usuario = get_object_or_404(Profesor, pk=request.session['username'])
			pacienteNuevo = Paciente.objects.get(pk=form['ci'].value())
			usuario.alumnos.add(pacienteNuevo)
			return redirect('/vistas/principalProfesor')
	else:
		form = AgregarPacienteForm()
	args = {'usuario': usuario, 'form': form}
	return render(request, 'vistas/agregarAlumno.html', args)


'''
Pagina inicial
'''
def home(request):
	return render(request, 'vistas/home.html', {})

def perfil(request):
	usuario = get_object_or_404(Usuario, pk=request.session['username'])
	
	form = ModificarUsuarioForm(request.POST, instance=usuario)
	if form.is_valid():
		nuevoUsuario = form.save(commit=False)
		request.session['username'] = form['username'].value()
		nuevoUsuario.save()
		if esRepresentante(form['username'].value()):
			return redirect('/vistas/principalRepresentante/')
		elif esProfesor(form['username'].value()):
			return redirect('/vistas/principalProfesor/')
		elif esMedico(form['username'].value()):
			return redirect('/vistas/principalMedico/')
		else:
			return redirect('/vistas/login/')
	else:
		form = ModificarUsuarioForm(instance=usuario)
	args = {'form': form, 'usuario': usuario}
	return render(request, 'vistas/perfil.html', args)

def perfilPaciente(request, ciPaciente):
	usuario = get_object_or_404(Usuario, pk=request.session['username'])
	paciente = Paciente.objects.get(pk=ciPaciente)
	form = AgregarPacienteForm(request.POST, instance=paciente)
	if form.is_valid():
		nuevoPaciente = form.save(commit=False)
		#request.session['username'] = form['username'].value()
		nuevoPaciente.save()
		if esRepresentante(usuario.username):
			return redirect('/vistas/principalRepresentante/')
		elif esProfesor(usuario.username):
			return redirect('/vistas/principalProfesor/')
		elif esMedico(usuario.username):
			return redirect('/vistas/principalMedico/')
		else:
			return redirect('/vistas/login/')
	else:
		form = AgregarPacienteForm(instance=paciente)
	args = {'form': form, 'usuario': usuario}
	return render(request, 'vistas/perfilPaciente.html', args)

vistas/templates/vistas/principalProfesor.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard</title>

    <!-- Fontfaces CSS-->
    <link href="{% static 'principal/css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'principal/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'principal/vendor/font-awesome-5/css/fontawesome-all.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'principal/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'principal/vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{% static 'principal/vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'principal/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'principal/vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'principal/vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'principal/vendor/slick/slick.css" rel="stylesheet' %}" media="all">
    <link href="{% static 'principal/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'principal/vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'principal/css/theme.css' %}" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper">
        <!-- HEADER MOBILE-->
        
        <!-- END HEADER MOBILE-->

        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="#">
                    <!--<img src="" alt="Sistema" />-->
                    Hola, {{ usuario.usuario.nombres }}
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        <li class="active has-sub">
                            <a class="js-arrow" href="#">
                                <i class="fas fa-home"></i>Home</a>
                        </li>
                        <li>
                            <a href="{% url 'vistas:perfil' %}">
                                <i class="fas fa-user"></i>Perfil</a>
                        </li>
                        <li>
                            <a href="{% url 'vistas:infoNutricional' %}">
                                <i class="fab fa-nutritionix"></i>Info. Nutricional</a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fas fa-info-circle"></i>Info. General</a>
                        </li>
                        <li>
                            <a href="{% url 'vistas:juegos' %}">
                                <i class="fas fa-gamepad"></i>Juegos</a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fas fa-signal"></i>Estadisticas</a>
                        </li>
                        <li>
                            <a href="{% url 'vistas:salir' %}">
                                <i class="fas fa-sign-out-alt"></i>Cerrar Sesión</a>
                        </li>
                        
                    </ul>
                </nav>
            </div>
        </aside>

        <!-- END MENU SIDEBAR-->

        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <header class="header-desktop">
                <!--<div class="section__content section__content--p30">
                    
                </div>-->
            </header>
            <!-- HEADER DESKTOP END-->

            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="overview-wrap">
                                    <h2 class="title-1">Alumnos</h2>
                                    <!--<button class="au-btn au-btn-icon au-btn--blue">
                                        <i class="zmdi zmdi-plus"></i>add item</button>-->
                                </div>
                            </div>
                        </div>
                        <div class="row m-t-25">
                            <div class="table-responsive table--no-card m-b-40">
                                    <table class="table table-borderless table-striped table-earning">
                                        <thead>
                                            <tr>
                                                <th>Nombres</th>
                                                <th>Apellidos</th>
                                                <th>Doc.Identidad</th>
                                                <th>Fecha de Nacimiento</th>
                                                <th>Condicion</th>
                                                
                                                <!--<th class="text-right">price</th>
                                                <th class="text-right">quantity</th>
                                                <th class="text-right">total</th>-->
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <!--<td class="text-right">$999.00</td>
                                            <td class="text-right">1</td>
                                            <td class="text-right">$999.00</td>-->
                                            
                                            {% for alumno in usuario.alumnos.all %}
                                            <tr>
                                                <td><a href="{% url 'vistas:perfilPaciente' ciPaciente=alumno.ci %}">{{ alumno.nombres }}</a></td>
                                                <td>{{ alumno.apellidos }}</td>
                                                <td>{{ alumno.ci }}</td>
                                                <td>{{ alumno.nacimiento }}</td>
                                                <td>{{ alumno.enfermedad }}</td>
                                                
                                            </tr>

                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>

                        </div>
                        <div class="row">


                        </div>
                        <div class="row">
                            <div class="col-lg-9">
                                <h2 class="title-1 m-b-25">Actividades</h2>
                                <div class="table-responsive table--no-card m-b-40">
                                    <table class="table table-borderless table-striped table-earning">
                                        <thead>
                                            <tr>
                                                <th>Hora</th>
                                                <th>Fecha</th>
                                                <th>Descripcion</th>
                                                <!--<th class="text-right">price</th>
                                                <th class="text-right">quantity</th>
                                                <th class="text-right">total</th>-->
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>14:00</td>
                                                <td>Dic. 13, 2001</td>
                                                <td>Actividad 1</td>
                                            </tr>

                                            
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <h2 class="title-1 m-b-25">Acciones</h2>
                                <div class="col-lg-9">
                                    <div class="row m-t-25">
                                        <a href="{% url 'vistas:agregarAlumno' %}"><button type="button" class="btn btn-primary">Agregar Alumno</button></a>
                                    </div>

                                    <div class="row m-t-25">
                                        <a href="#"><button type="button" class="btn btn-danger">Eliminar Alumno</button></a>
                                    </div>
                                </div>
                                <!--<h2 class="title-1 m-b-25">Puntuaciones</h2>
                                </div>-->
                            </div>
                        </div>
                        <div class="row">
                            <!--<div class="col-lg-6">
                        </div>-->
                        <div class="row">
                            <div class="col-md-12">
                                <div class="copyright">
                                    <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>

    </div>

    <!-- Jquery JS-->
    <script src="{% static 'principal/vendor/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap JS-->
    <script src="{% static 'principal/vendor/bootstrap-4.1/popper.min.js' %}"></script>
    <script src="{% static 'principal/vendor/bootstrap-4.1/bootstrap.min.js' %}"></script>
    <!-- Vendor JS       -->
    <script src="{% static 'principal/vendor/slick/slick.min.js' %}">
    </script>
    <script src="{% static 'principal/vendor/wow/wow.min.js' %}"></script>
    <script src="{% static 'principal/vendor/animsition/animsition.min.js' %}"></script>
    <script src="{% static 'principal/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js' %}">
    </script>
    <script src="{% static 'principal/vendor/counter-up/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'principal/vendor/counter-up/jquery.counterup.min.js' %}">
    </script>
    <script src="{% static 'principal/vendor/circle-progress/circle-progress.min.js' %}"></script>
    <script src="{% static 'principal/vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'principal/vendor/chartjs/Chart.bundle.min.js' %}"></script>
    <script src="{% static 'principal/vendor/select2/select2.min.js' %}">
    </script>

    <!-- Main JS-->
    <script src="{% static 'principal/js/main.js' %}"></script>

</body>

</html>
<!-- end document-->